/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DirectionsCoordinatesGet500Response from '../model/DirectionsCoordinatesGet500Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the directionsCoordinatesGet operation.
     * @callback module:api/DefaultApi~directionsCoordinatesGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get directions with multiple coordinates
     * @param {String} points 
     * @param {module:api/DefaultApi~directionsCoordinatesGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    directionsCoordinatesGet(points, callback) {
      let postBody = null;
      // verify the required parameter 'points' is set
      if (points === undefined || points === null) {
        throw new Error("Missing the required parameter 'points' when calling directionsCoordinatesGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'points': points
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/directions/coordinates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
