/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GasPricesProvinceCityGet200Response from '../model/GasPricesProvinceCityGet200Response';
import GasPricesProvinceCityGet500Response from '../model/GasPricesProvinceCityGet500Response';

/**
* GasApi service.
* @module api/GasApiApi
* @version 1.0.0
*/
export default class GasApiApi {

    /**
    * Constructs a new GasApiApi. 
    * @alias module:api/GasApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the gasPricesProvinceCityGet operation.
     * @callback module:api/GasApiApi~gasPricesProvinceCityGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GasPricesProvinceCityGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get gas prices for a specific province and city
     * @param {String} province The province to retrieve gas prices for
     * @param {String} city The city to retrieve gas prices for
     * @param {module:api/GasApiApi~gasPricesProvinceCityGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GasPricesProvinceCityGet200Response}
     */
    gasPricesProvinceCityGet(province, city, callback) {
      let postBody = null;
      // verify the required parameter 'province' is set
      if (province === undefined || province === null) {
        throw new Error("Missing the required parameter 'province' when calling gasPricesProvinceCityGet");
      }
      // verify the required parameter 'city' is set
      if (city === undefined || city === null) {
        throw new Error("Missing the required parameter 'city' when calling gasPricesProvinceCityGet");
      }

      let pathParams = {
        'province': province,
        'city': city
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GasPricesProvinceCityGet200Response;
      return this.apiClient.callApi(
        '/gas-prices/{province}/{city}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
