/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DirectionsGet200Response from '../model/DirectionsGet200Response';
import DirectionsGet500Response from '../model/DirectionsGet500Response';

/**
* ServiceRoute service.
* @module api/ServiceRouteApi
* @version 1.0.0
*/
export default class ServiceRouteApi {

    /**
    * Constructs a new ServiceRouteApi. 
    * @alias module:api/ServiceRouteApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the directionsGet operation.
     * @callback module:api/ServiceRouteApi~directionsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DirectionsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get directions
     * @param {module:api/ServiceRouteApi~directionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DirectionsGet200Response}
     */
    directionsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DirectionsGet200Response;
      return this.apiClient.callApi(
        '/directions/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
