/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DirectionsCoordinatesGet500Response from './model/DirectionsCoordinatesGet500Response';
import GasPricesProvinceCityGet200Response from './model/GasPricesProvinceCityGet200Response';
import GasPricesProvinceCityGet200ResponseGasPricesInner from './model/GasPricesProvinceCityGet200ResponseGasPricesInner';
import GasPricesProvinceCityGet500Response from './model/GasPricesProvinceCityGet500Response';
import UsersLoginJwtPostRequest from './model/UsersLoginJwtPostRequest';
import UsersLoginPostRequest from './model/UsersLoginPostRequest';
import UsersUserIdCarsPostRequest from './model/UsersUserIdCarsPostRequest';
import UsersUserIdPutRequest from './model/UsersUserIdPutRequest';
import UsersUserIdStationsPostRequest from './model/UsersUserIdStationsPostRequest';
import CarsApi from './api/CarsApi';
import DefaultApi from './api/DefaultApi';
import GasApiApi from './api/GasApiApi';
import StationsApi from './api/StationsApi';
import UsersApi from './api/UsersApi';


/**
* This is the official API of GasFein.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GasFeinApi = require('index'); // See note below*.
* var xxxSvc = new GasFeinApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GasFeinApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GasFeinApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GasFeinApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DirectionsCoordinatesGet500Response model constructor.
     * @property {module:model/DirectionsCoordinatesGet500Response}
     */
    DirectionsCoordinatesGet500Response,

    /**
     * The GasPricesProvinceCityGet200Response model constructor.
     * @property {module:model/GasPricesProvinceCityGet200Response}
     */
    GasPricesProvinceCityGet200Response,

    /**
     * The GasPricesProvinceCityGet200ResponseGasPricesInner model constructor.
     * @property {module:model/GasPricesProvinceCityGet200ResponseGasPricesInner}
     */
    GasPricesProvinceCityGet200ResponseGasPricesInner,

    /**
     * The GasPricesProvinceCityGet500Response model constructor.
     * @property {module:model/GasPricesProvinceCityGet500Response}
     */
    GasPricesProvinceCityGet500Response,

    /**
     * The UsersLoginJwtPostRequest model constructor.
     * @property {module:model/UsersLoginJwtPostRequest}
     */
    UsersLoginJwtPostRequest,

    /**
     * The UsersLoginPostRequest model constructor.
     * @property {module:model/UsersLoginPostRequest}
     */
    UsersLoginPostRequest,

    /**
     * The UsersUserIdCarsPostRequest model constructor.
     * @property {module:model/UsersUserIdCarsPostRequest}
     */
    UsersUserIdCarsPostRequest,

    /**
     * The UsersUserIdPutRequest model constructor.
     * @property {module:model/UsersUserIdPutRequest}
     */
    UsersUserIdPutRequest,

    /**
     * The UsersUserIdStationsPostRequest model constructor.
     * @property {module:model/UsersUserIdStationsPostRequest}
     */
    UsersUserIdStationsPostRequest,

    /**
    * The CarsApi service constructor.
    * @property {module:api/CarsApi}
    */
    CarsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The GasApiApi service constructor.
    * @property {module:api/GasApiApi}
    */
    GasApiApi,

    /**
    * The StationsApi service constructor.
    * @property {module:api/StationsApi}
    */
    StationsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
