/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectionsGet200ResponseDirectionsInner model module.
 * @module model/DirectionsGet200ResponseDirectionsInner
 * @version 1.0.0
 */
class DirectionsGet200ResponseDirectionsInner {
    /**
     * Constructs a new <code>DirectionsGet200ResponseDirectionsInner</code>.
     * @alias module:model/DirectionsGet200ResponseDirectionsInner
     */
    constructor() { 
        
        DirectionsGet200ResponseDirectionsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DirectionsGet200ResponseDirectionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectionsGet200ResponseDirectionsInner} obj Optional instance to populate.
     * @return {module:model/DirectionsGet200ResponseDirectionsInner} The populated <code>DirectionsGet200ResponseDirectionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionsGet200ResponseDirectionsInner();

            if (data.hasOwnProperty('station')) {
                obj['station'] = ApiClient.convertToType(data['station'], 'String');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DirectionsGet200ResponseDirectionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DirectionsGet200ResponseDirectionsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['station'] && !(typeof data['station'] === 'string' || data['station'] instanceof String)) {
            throw new Error("Expected the field `station` to be a primitive type in the JSON string but got " + data['station']);
        }
        // ensure the json data is a string
        if (data['distance'] && !(typeof data['distance'] === 'string' || data['distance'] instanceof String)) {
            throw new Error("Expected the field `distance` to be a primitive type in the JSON string but got " + data['distance']);
        }

        return true;
    }


}



/**
 * The station providing the directions
 * @member {String} station
 */
DirectionsGet200ResponseDirectionsInner.prototype['station'] = undefined;

/**
 * The distance to the destination
 * @member {String} distance
 */
DirectionsGet200ResponseDirectionsInner.prototype['distance'] = undefined;






export default DirectionsGet200ResponseDirectionsInner;

