/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectionsCoordinatesPostRequestInnerOneOf model module.
 * @module model/DirectionsCoordinatesPostRequestInnerOneOf
 * @version 1.0.0
 */
class DirectionsCoordinatesPostRequestInnerOneOf {
    /**
     * Constructs a new <code>DirectionsCoordinatesPostRequestInnerOneOf</code>.
     * @alias module:model/DirectionsCoordinatesPostRequestInnerOneOf
     * @param longitude {Number} 
     * @param latitude {Number} 
     */
    constructor(longitude, latitude) { 
        
        DirectionsCoordinatesPostRequestInnerOneOf.initialize(this, longitude, latitude);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, longitude, latitude) { 
        obj['longitude'] = longitude;
        obj['latitude'] = latitude;
    }

    /**
     * Constructs a <code>DirectionsCoordinatesPostRequestInnerOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectionsCoordinatesPostRequestInnerOneOf} obj Optional instance to populate.
     * @return {module:model/DirectionsCoordinatesPostRequestInnerOneOf} The populated <code>DirectionsCoordinatesPostRequestInnerOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionsCoordinatesPostRequestInnerOneOf();

            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DirectionsCoordinatesPostRequestInnerOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DirectionsCoordinatesPostRequestInnerOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DirectionsCoordinatesPostRequestInnerOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DirectionsCoordinatesPostRequestInnerOneOf.RequiredProperties = ["longitude", "latitude"];

/**
 * @member {Number} longitude
 */
DirectionsCoordinatesPostRequestInnerOneOf.prototype['longitude'] = undefined;

/**
 * @member {Number} latitude
 */
DirectionsCoordinatesPostRequestInnerOneOf.prototype['latitude'] = undefined;






export default DirectionsCoordinatesPostRequestInnerOneOf;

