/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectionsGet200ResponseDirectionsInner from './DirectionsGet200ResponseDirectionsInner';

/**
 * The DirectionsGet200Response model module.
 * @module model/DirectionsGet200Response
 * @version 1.0.0
 */
class DirectionsGet200Response {
    /**
     * Constructs a new <code>DirectionsGet200Response</code>.
     * @alias module:model/DirectionsGet200Response
     */
    constructor() { 
        
        DirectionsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DirectionsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectionsGet200Response} obj Optional instance to populate.
     * @return {module:model/DirectionsGet200Response} The populated <code>DirectionsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionsGet200Response();

            if (data.hasOwnProperty('directions')) {
                obj['directions'] = ApiClient.convertToType(data['directions'], [DirectionsGet200ResponseDirectionsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DirectionsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DirectionsGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['directions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['directions'])) {
                throw new Error("Expected the field `directions` to be an array in the JSON data but got " + data['directions']);
            }
            // validate the optional field `directions` (array)
            for (const item of data['directions']) {
                DirectionsGet200ResponseDirectionsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DirectionsGet200ResponseDirectionsInner>} directions
 */
DirectionsGet200Response.prototype['directions'] = undefined;






export default DirectionsGet200Response;

