/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectionsCoordinatesPostRequestInnerOneOf from './DirectionsCoordinatesPostRequestInnerOneOf';
import DirectionsCoordinatesPostRequestInnerOneOf1 from './DirectionsCoordinatesPostRequestInnerOneOf1';

/**
 * The DirectionsCoordinatesPostRequestInner model module.
 * @module model/DirectionsCoordinatesPostRequestInner
 * @version 1.0.0
 */
class DirectionsCoordinatesPostRequestInner {
    /**
     * Constructs a new <code>DirectionsCoordinatesPostRequestInner</code>.
     * @alias module:model/DirectionsCoordinatesPostRequestInner
     * @param {(module:model/DirectionsCoordinatesPostRequestInnerOneOf|module:model/DirectionsCoordinatesPostRequestInnerOneOf1)} instance The actual instance to initialize DirectionsCoordinatesPostRequestInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "DirectionsCoordinatesPostRequestInnerOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                DirectionsCoordinatesPostRequestInnerOneOf.validateJSON(instance); // throw an exception if no match
                // create DirectionsCoordinatesPostRequestInnerOneOf from JS object
                this.actualInstance = DirectionsCoordinatesPostRequestInnerOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into DirectionsCoordinatesPostRequestInnerOneOf
            errorMessages.push("Failed to construct DirectionsCoordinatesPostRequestInnerOneOf: " + err)
        }

        try {
            if (typeof instance === "DirectionsCoordinatesPostRequestInnerOneOf1") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                DirectionsCoordinatesPostRequestInnerOneOf1.validateJSON(instance); // throw an exception if no match
                // create DirectionsCoordinatesPostRequestInnerOneOf1 from JS object
                this.actualInstance = DirectionsCoordinatesPostRequestInnerOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into DirectionsCoordinatesPostRequestInnerOneOf1
            errorMessages.push("Failed to construct DirectionsCoordinatesPostRequestInnerOneOf1: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `DirectionsCoordinatesPostRequestInner` with oneOf schemas DirectionsCoordinatesPostRequestInnerOneOf, DirectionsCoordinatesPostRequestInnerOneOf1. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `DirectionsCoordinatesPostRequestInner` with oneOf schemas DirectionsCoordinatesPostRequestInnerOneOf, DirectionsCoordinatesPostRequestInnerOneOf1. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>DirectionsCoordinatesPostRequestInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectionsCoordinatesPostRequestInner} obj Optional instance to populate.
     * @return {module:model/DirectionsCoordinatesPostRequestInner} The populated <code>DirectionsCoordinatesPostRequestInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new DirectionsCoordinatesPostRequestInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>DirectionsCoordinatesPostRequestInnerOneOf</code>, <code>DirectionsCoordinatesPostRequestInnerOneOf1</code>.
     * @return {(module:model/DirectionsCoordinatesPostRequestInnerOneOf|module:model/DirectionsCoordinatesPostRequestInnerOneOf1)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>DirectionsCoordinatesPostRequestInnerOneOf</code>, <code>DirectionsCoordinatesPostRequestInnerOneOf1</code>.
     * @param {(module:model/DirectionsCoordinatesPostRequestInnerOneOf|module:model/DirectionsCoordinatesPostRequestInnerOneOf1)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = DirectionsCoordinatesPostRequestInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of DirectionsCoordinatesPostRequestInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/DirectionsCoordinatesPostRequestInner} An instance of DirectionsCoordinatesPostRequestInner.
     */
    static fromJSON = function(json_string){
        return DirectionsCoordinatesPostRequestInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Number} longitude
 */
DirectionsCoordinatesPostRequestInner.prototype['longitude'] = undefined;

/**
 * @member {Number} latitude
 */
DirectionsCoordinatesPostRequestInner.prototype['latitude'] = undefined;

/**
 * @member {String} address
 */
DirectionsCoordinatesPostRequestInner.prototype['address'] = undefined;


DirectionsCoordinatesPostRequestInner.OneOf = ["DirectionsCoordinatesPostRequestInnerOneOf", "DirectionsCoordinatesPostRequestInnerOneOf1"];

export default DirectionsCoordinatesPostRequestInner;

