/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectionsCoordinatesPostRequestInnerOneOf1 model module.
 * @module model/DirectionsCoordinatesPostRequestInnerOneOf1
 * @version 1.0.0
 */
class DirectionsCoordinatesPostRequestInnerOneOf1 {
    /**
     * Constructs a new <code>DirectionsCoordinatesPostRequestInnerOneOf1</code>.
     * @alias module:model/DirectionsCoordinatesPostRequestInnerOneOf1
     * @param address {String} 
     */
    constructor(address) { 
        
        DirectionsCoordinatesPostRequestInnerOneOf1.initialize(this, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address) { 
        obj['address'] = address;
    }

    /**
     * Constructs a <code>DirectionsCoordinatesPostRequestInnerOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectionsCoordinatesPostRequestInnerOneOf1} obj Optional instance to populate.
     * @return {module:model/DirectionsCoordinatesPostRequestInnerOneOf1} The populated <code>DirectionsCoordinatesPostRequestInnerOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionsCoordinatesPostRequestInnerOneOf1();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DirectionsCoordinatesPostRequestInnerOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DirectionsCoordinatesPostRequestInnerOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DirectionsCoordinatesPostRequestInnerOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}

DirectionsCoordinatesPostRequestInnerOneOf1.RequiredProperties = ["address"];

/**
 * @member {String} address
 */
DirectionsCoordinatesPostRequestInnerOneOf1.prototype['address'] = undefined;






export default DirectionsCoordinatesPostRequestInnerOneOf1;

