/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GasPricesProvinceCityGet200ResponseGasPricesInner from './GasPricesProvinceCityGet200ResponseGasPricesInner';

/**
 * The GasPricesProvinceCityGet200Response model module.
 * @module model/GasPricesProvinceCityGet200Response
 * @version 1.0.0
 */
class GasPricesProvinceCityGet200Response {
    /**
     * Constructs a new <code>GasPricesProvinceCityGet200Response</code>.
     * @alias module:model/GasPricesProvinceCityGet200Response
     */
    constructor() { 
        
        GasPricesProvinceCityGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GasPricesProvinceCityGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GasPricesProvinceCityGet200Response} obj Optional instance to populate.
     * @return {module:model/GasPricesProvinceCityGet200Response} The populated <code>GasPricesProvinceCityGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GasPricesProvinceCityGet200Response();

            if (data.hasOwnProperty('gasPrices')) {
                obj['gasPrices'] = ApiClient.convertToType(data['gasPrices'], [GasPricesProvinceCityGet200ResponseGasPricesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GasPricesProvinceCityGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GasPricesProvinceCityGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['gasPrices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['gasPrices'])) {
                throw new Error("Expected the field `gasPrices` to be an array in the JSON data but got " + data['gasPrices']);
            }
            // validate the optional field `gasPrices` (array)
            for (const item of data['gasPrices']) {
                GasPricesProvinceCityGet200ResponseGasPricesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GasPricesProvinceCityGet200ResponseGasPricesInner>} gasPrices
 */
GasPricesProvinceCityGet200Response.prototype['gasPrices'] = undefined;






export default GasPricesProvinceCityGet200Response;

