/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GasPricesProvinceCityGet200ResponseGasPricesInner model module.
 * @module model/GasPricesProvinceCityGet200ResponseGasPricesInner
 * @version 1.0.0
 */
class GasPricesProvinceCityGet200ResponseGasPricesInner {
    /**
     * Constructs a new <code>GasPricesProvinceCityGet200ResponseGasPricesInner</code>.
     * @alias module:model/GasPricesProvinceCityGet200ResponseGasPricesInner
     */
    constructor() { 
        
        GasPricesProvinceCityGet200ResponseGasPricesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GasPricesProvinceCityGet200ResponseGasPricesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GasPricesProvinceCityGet200ResponseGasPricesInner} obj Optional instance to populate.
     * @return {module:model/GasPricesProvinceCityGet200ResponseGasPricesInner} The populated <code>GasPricesProvinceCityGet200ResponseGasPricesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GasPricesProvinceCityGet200ResponseGasPricesInner();

            if (data.hasOwnProperty('station')) {
                obj['station'] = ApiClient.convertToType(data['station'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GasPricesProvinceCityGet200ResponseGasPricesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GasPricesProvinceCityGet200ResponseGasPricesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['station'] && !(typeof data['station'] === 'string' || data['station'] instanceof String)) {
            throw new Error("Expected the field `station` to be a primitive type in the JSON string but got " + data['station']);
        }

        return true;
    }


}



/**
 * The name of the gas station
 * @member {String} station
 */
GasPricesProvinceCityGet200ResponseGasPricesInner.prototype['station'] = undefined;

/**
 * The gas price at the station
 * @member {Number} price
 */
GasPricesProvinceCityGet200ResponseGasPricesInner.prototype['price'] = undefined;






export default GasPricesProvinceCityGet200ResponseGasPricesInner;

