/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersUserIdStationsPostRequest model module.
 * @module model/UsersUserIdStationsPostRequest
 * @version 1.0.0
 */
class UsersUserIdStationsPostRequest {
    /**
     * Constructs a new <code>UsersUserIdStationsPostRequest</code>.
     * @alias module:model/UsersUserIdStationsPostRequest
     */
    constructor() { 
        
        UsersUserIdStationsPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersUserIdStationsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersUserIdStationsPostRequest} obj Optional instance to populate.
     * @return {module:model/UsersUserIdStationsPostRequest} The populated <code>UsersUserIdStationsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersUserIdStationsPostRequest();

            if (data.hasOwnProperty('stationName')) {
                obj['stationName'] = ApiClient.convertToType(data['stationName'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersUserIdStationsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersUserIdStationsPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['stationName'] && !(typeof data['stationName'] === 'string' || data['stationName'] instanceof String)) {
            throw new Error("Expected the field `stationName` to be a primitive type in the JSON string but got " + data['stationName']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}



/**
 * @member {String} stationName
 */
UsersUserIdStationsPostRequest.prototype['stationName'] = undefined;

/**
 * @member {String} address
 */
UsersUserIdStationsPostRequest.prototype['address'] = undefined;

/**
 * @member {Number} price
 */
UsersUserIdStationsPostRequest.prototype['price'] = undefined;






export default UsersUserIdStationsPostRequest;

