/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersUserIdCarsPostRequest model module.
 * @module model/UsersUserIdCarsPostRequest
 * @version 1.0.0
 */
class UsersUserIdCarsPostRequest {
    /**
     * Constructs a new <code>UsersUserIdCarsPostRequest</code>.
     * @alias module:model/UsersUserIdCarsPostRequest
     */
    constructor() { 
        
        UsersUserIdCarsPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersUserIdCarsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersUserIdCarsPostRequest} obj Optional instance to populate.
     * @return {module:model/UsersUserIdCarsPostRequest} The populated <code>UsersUserIdCarsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersUserIdCarsPostRequest();

            if (data.hasOwnProperty('make')) {
                obj['make'] = ApiClient.convertToType(data['make'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('fuelType')) {
                obj['fuelType'] = ApiClient.convertToType(data['fuelType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersUserIdCarsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersUserIdCarsPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['make'] && !(typeof data['make'] === 'string' || data['make'] instanceof String)) {
            throw new Error("Expected the field `make` to be a primitive type in the JSON string but got " + data['make']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['color'] && !(typeof data['color'] === 'string' || data['color'] instanceof String)) {
            throw new Error("Expected the field `color` to be a primitive type in the JSON string but got " + data['color']);
        }
        // ensure the json data is a string
        if (data['fuelType'] && !(typeof data['fuelType'] === 'string' || data['fuelType'] instanceof String)) {
            throw new Error("Expected the field `fuelType` to be a primitive type in the JSON string but got " + data['fuelType']);
        }

        return true;
    }


}



/**
 * @member {String} make
 */
UsersUserIdCarsPostRequest.prototype['make'] = undefined;

/**
 * @member {String} model
 */
UsersUserIdCarsPostRequest.prototype['model'] = undefined;

/**
 * @member {Number} year
 */
UsersUserIdCarsPostRequest.prototype['year'] = undefined;

/**
 * @member {String} color
 */
UsersUserIdCarsPostRequest.prototype['color'] = undefined;

/**
 * @member {String} fuelType
 */
UsersUserIdCarsPostRequest.prototype['fuelType'] = undefined;






export default UsersUserIdCarsPostRequest;

