/**
 * GasFein API
 * This is the official API of GasFein
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersLoginJwtPostRequest model module.
 * @module model/UsersLoginJwtPostRequest
 * @version 1.0.0
 */
class UsersLoginJwtPostRequest {
    /**
     * Constructs a new <code>UsersLoginJwtPostRequest</code>.
     * @alias module:model/UsersLoginJwtPostRequest
     */
    constructor() { 
        
        UsersLoginJwtPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersLoginJwtPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersLoginJwtPostRequest} obj Optional instance to populate.
     * @return {module:model/UsersLoginJwtPostRequest} The populated <code>UsersLoginJwtPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersLoginJwtPostRequest();

            if (data.hasOwnProperty('jwt')) {
                obj['jwt'] = ApiClient.convertToType(data['jwt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersLoginJwtPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersLoginJwtPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['jwt'] && !(typeof data['jwt'] === 'string' || data['jwt'] instanceof String)) {
            throw new Error("Expected the field `jwt` to be a primitive type in the JSON string but got " + data['jwt']);
        }

        return true;
    }


}



/**
 * @member {String} jwt
 */
UsersLoginJwtPostRequest.prototype['jwt'] = undefined;






export default UsersLoginJwtPostRequest;

