name: Update Contributors

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main 
      - develop 
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Contributors in README
        uses: akhilmhdh/contributors-readme-action@v2.0
        with:
          action: update
          readme-path: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
